name: detectinatorul
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pytorch-cuda==11.8
  - pytorch==2.1.0
  - torchaudio==2.1.0
  - torchvision==0.16.0
  - keras=3.0
  - matplotlib
  - scikit-learn
  - pandas
  - ipykernel
  - seaborn
  - spyder-kernels=2.5
